### ISSUE TITLE
Scala metals workspace error

### ISSUE THREAD

**Issue by gbrennon** [scala/scala3.g8#85]
Hey folks,

How are u doing?

I've been trying to use this template using scala metals as my "IDE" and it always returns me the same error when trying to import the build.

```
Build server currently being used is Bloop v1.4.12.

These are the installed build targets for this workspace. One build target corresponds to one classpath. For example, normally one sbt project maps to two build targets: main and test.

Build target | Type | Diagnostics | Interactive | Semanticdb | Debugging | Java support | Recommendation
-- | -- | -- | -- | -- | -- | -- | --
root | Scala 3.1.0 | ✅ | ✅ | ✅ | ✅ | ✅ |  
root-test | Scala 3.1.0 | ✅ | ✅ | ✅ | ✅ | ✅ |  
gitpod-g8-build | sbt 1.6.1 | ⚠️ | ✅ | ✅ | ❌ | ✅ | Diagnostics and debugging for sbt are not supported currently.


```

What should I do?

**Comment by SethTisue** [comment]
Does Metals work for you for any Scala 2 or Scala 3 projects at all? Is it only projects made using this template that fail...?

The error line mentions Gitpod. I'm wondering how that's entering into this. Are you using Gitpod?

**Comment by ckipp01** [comment]
Just jumping in here to say that this should be addressed with newer versions of Metals. You're seeing a few different messages:

1. The X on java support for the `*-build` target. This is expected as your actual sbt build doesn't support Java. The warning since this has been fixed however.
2. Same with debugging, debugging in supported in Scala/Java targets, but not your actual sbt build target.
3. The Diagnostics message should also be fixed
Please do try the latest Metals and report any problems you might be experiencing over there.
